### PR TITLE
Adding mergerules command to generate a merged rule file for Clang rules

### PR DESCRIPTION
**Pull request by aallrd**
Hello,

I would like to contribute this `mergerules` function used to create a _clangtidy_merged.xml_ file merging the output of the _generate_clangtidy_resources_ script:
- _clangtidy_new.xml_ (clang-tidy rules)
- _diagnostic_new.xml_ (clang diagnostics rules)

It was mentioned in #2378 that this process was manual and I needed a way to have it automated.

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/2382)

### CODE REVIEW

**Comment by guwirth** [comment]
Hi @aallrd,

thanks for your contribution, I will have a look to it.

Regards,

**Comment by guwirth** [comment]
The automated reading and creation of new rule files cannot be fully automated. Manual corrections are often necessary for the final version of the rule files. The automatically created file "clangtidy_merged.xml" can therefore probably not be used 1:1.

@aallrd Or what experience have you made?

**Comment by aallrd** [comment]
I compared the list of clangtidy rules (keys) from three files:
- The _clangtidy.xml_ from the 2.0.6.2925 release JAR (_sonar-cxx-plugin-2.0.6.2925.jar_): 1316 rules
  - Sourced from llvmorg-14-init-8123-ga875e6e1225a
- The _clangtidy.xml_ from the 2.0.7.3119 release JAR (_sonar-cxx-plugin-2.0.7.3119.jar_): 1340 rules
  - Sourced from llvmorg-15-init-2831-geb3e09c9bf1d
- The _clangtidy_merged.xml_ built using the scripts from my custom LLVM/Clang sources: 1347 rules
  - 14 custom rules: 1333 rules
  - Sourced from [d7986bf0111](https://github.com/llvm/llvm-project/commit/d7986bf0111)

Here is the diff of rules between the _2.0.7.3119_ release JAR and my _clangtidy_merged.xml_:
```
+     <key>abseil-cleanup-ctad</key>
+     <key>misc-unused-function</key>
+     <key>misc-unused-variable</key>
+     <key>modernize-deprecated-bind1st</key>
-     <key>bugprone-shared-ptr-array-mismatch</key>
-     <key>clang-diagnostic-always-inline-coroutine</key>
-     <key>clang-diagnostic-requires-expression</key>
-     <key>clang-diagnostic-return-std-move</key>
-     <key>clang-diagnostic-unaligned-access</key>
-     <key>clang-diagnostic-unqualified-std-cast-call</key>
-     <key>clang-diagnostic-unsupported-abi</key>
-     <key>misc-misleading-bidirectional</key>
-     <key>readability-container-contains</key>
-     <key>readability-data-pointer</key>
-     <key>readability-duplicate-include</key>
```

The added _misc_ and _modernize_ are expected because we kept them in our LLVM/Clang fork while they are gone upstream.
The missing ones seem to have been added somewhere in the past ~4 months and our fork is a bit older than that,

From this comparison I would say the function did a correct job merging the files and created a valid and suitable _clangtidy_merged.xml_ for production.

What are the manual corrections you are doing on your side on the _clangtidy.xml_ file?

**Comment by guwirth** [comment]
@aallrd in the past I had to adapt some keys and descriptions manually after creating xml files from a new Clang version. After executing your script and comparing the result with [clangtidy.xml](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/main/resources/clangtidy.xml) you should see the differences.

Your script extension is definitely an improvement and I will merge it. Thanks again for that!
What I doubt is if you can run everything automated?

**Pull request merged**
