### PR TITLE
fix rule CycleBetweenPackages Sqale remediation parameters

### PR DESCRIPTION
**Pull request by Bertk**
see #734

### CODE REVIEW

**Comment by guwirth** [comment]
Wait for

> The cxx-checks sqale definitions should be removed from sonar-cxx-plugin/src/main/resources/com/sonar/sqale/cxx-model.xml.

before I merge this?

**Comment by Bertk** [comment]
The cxx-model.xml file does not contain any cxx-checks definitions. This was removed before with https://github.com/guwirth/sonar-cxx/commit/b49577b556ab5bd72e205a6205dcf7a1629646ab.
I also deleted the obsolete cxx-model-project files because they are not in sync with cxx-model.xml.

**Comment by jmecosta** [comment]
Ok that's good, so all should be oknow ?

**Comment by Bertk** [comment]
I am not sure. There are other checks which use ```@SqaleConstantRemediation``` as well and this is a potential background tasks exception (SQ 5.2 or 5.3). I have not all checks activated but some of them and they did not create an exception.
So for now - I assume the issue is fixed and only 'cxx:CycleBetweenPackages' created an exception. Unfortunately I do not know why this is limited to 'cxx:CycleBetweenPackages'
@guwirth: When will you create the next RC? We should now ready to target SQ5.3 aren't we?

**Comment by guwirth** [comment]
@Bertk over AppVeyor there is always the latest plugin available. I did no tests with 5.3 up to now and integration tests are also red. The issue list is also still very long :-(

**Comment by guwirth** [comment]
PR :+1:

**Pull request merged**
