### PR TITLE
update pom for SQ 5.2+

### PR DESCRIPTION
**Pull request by guwirth**
org.sonarsource.parent=31
sonar.version=4.5.4

### CODE REVIEW

**Comment by guwirth** [comment]
```
[INFO] --- maven-license-plugin:1.10.b1:check (enforce-license-headers) @ cxx-squid ---
[INFO] Checking licenses...
[INFO] Missing header in: /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-squid/src/main/java/org/sonar/cxx/parser/package-info.java
[INFO] Missing header in: /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-squid/src/main/java/org/sonar/cxx/package-info.java
...
```

**Comment by jmecosta** [comment]
Run build with -X it should print the requires header to be place in files, Regarding owner I don't mind the way it is

**Comment by guwirth** [comment]
Seems to be:
```
[DEBUG]   (f) properties = {license.mailto=mailto:contact AT sonarsource DOT com, license.owner=Waleri Enns and CONTACT Software GmbH, license.title=Sonar C++ Plugin (Community), license.years=2011-2016}
```

```
Sonar C++ Plugin (Community)
Copyright (C) 2011-2016 Waleri Enns and CONTACT Software GmbH
mailto:contact AT sonarsource DOT com

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 3 of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program; if not, write to the Free Software Foundation,
Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
```

**Comment by jmecosta** [comment]
interesting, seems they change this in plugin project see
https://github.com/SonarSource/sonar-dotnet-tests-library/commit/72ce9ba0bbfa97fc2cc5bff3dca4544d5c26cf8a

perhaps its best if we use our headers?

**Comment by jmecosta** [comment]
i have something like this in one plugin:

https://github.com/jmecsoftware/sonar-msbuild-plugin/blob/master/sonar-msbuild-plugin/src/main/java/org/sonar/plugins/msbuild/MSBuildAbastractParser.java

**Comment by jmecosta** [comment]
so we need this: https://github.com/jmecsoftware/sonar-msbuild-plugin/blob/master/sonar-msbuild-plugin/src/license-header.txt and this https://github.com/jmecsoftware/sonar-msbuild-plugin/blob/master/sonar-msbuild-plugin/pom.xml#L186

**Comment by guwirth** [comment]
There are still some problems with org.sonar.api.batch.fs.internal.DefaultFileSystem and some unit tests. Seems to be a problem with slash / backslash Linux / Windows. Nevertheless I merge this and fix the commented out tests in the next PR.

**Pull request merged**
