### PR TITLE
Refactor/highlighting

### PR DESCRIPTION
**Pull request by guwirth**
remove deprecated classes:
* org.sonar.api.web.CodeColorizerFormat
* import org.sonar.colorizer.CDocTokenizer
* import org.sonar.colorizer.CppDocTokenizer
* import org.sonar.colorizer.KeywordsTokenizer
* import org.sonar.colorizer.LiteralTokenizer
* import org.sonar.colorizer.RegexpTokenizer
* import org.sonar.colorizer.Tokenizer

use new org.sonar.api.batch.sensor.highlighting.NewHighlighting instead

### CODE REVIEW

**Comment by guwirth** [comment]
@all have some problems with preprocessor directives and line splicing (\  followed by new line character). The preprocessor is joining such lines and removes \ and new line character. Inside of the trivia it seems no more possible to detect the original number of lines and line lengths.

sample:
```C++
#define FUNC(a) \
   auto value = a; \
   return value ? 0 : 1;
```
results in:
```C++
#define FUNC(a)    auto value = a;    return value ? 0 : 1;
```

someone an idea how to handle this?

**Comment by guwirth** [comment]
@all: tested and ready to review

**Comment by jmecosta** [comment]
Great you manage to make it work, looks good to me.

**Comment by jmecosta** [comment]
Great you manage to make it work, looks good to me.

**Pull request merged**
