### PR TITLE
 add metric COMPLEXITY_IN_CLASSES and COMPLEXITY_IN_FUNCTIONS

### LINKED ISSUE #747: SQ 5.4: now requires the metrics complexity_in_classes  and complexity_in_functions
**Problem: value of class complexity is different with SQ 5.2+**

SQ support: Thanks for the project, we've been able to investigate and could understand your issue. As we're computing the complexity per class in a different way, the value can now be different but this come in fact from another issue : the plugin doesn't compute the measure 'complexity_in_classs' so there's a fallback mechanism to use the complexity instead. 

But this is not the right way to do : we should only rely on the complexity_in_classes and not anymore rely on the complexity. This will be done by https://jira.sonarsource.com/browse/SONAR-7169.

* link https://groups.google.com/forum/#!topic/sonarqube/8hV4EUauzJE
* related to #721

### PR DESCRIPTION
**Pull request by guwirth**
close #747

### CODE REVIEW

**Comment by guwirth** [comment]
@all someone familiar with class and function metrics and can give some hints? Still not working...

**Comment by jmecosta** [comment]
@guwirth do we really need it?

the c# plugin does not feed this metric to sonar.

https://github.com/SonarSource/sonar-csharp/blob/master/src/main/java/org/sonar/plugins/csharp/CSharpSensor.java

**Comment by guwirth** [comment]
@jmecosta if I understand this right then yes?
https://jira.sonarsource.com/browse/SONAR-7169

**Comment by jmecosta** [comment]
we dont have  a check "class should not be to complex", monitoring a
complexity of a function is imo is enough. as of now i dont think we use
this metric for anything.

would be better to for example just raise issues for a class that has high
complexity. we dont even have class distribution so really dont know if its
taht important

**Comment by guwirth** [comment]
With COMPLEXITY_IN_CLASSES you are maybe right, but still think something is wrong:
Current branch with SQ5.4-RC2: Assertion Failed: function_complexity is actually None
https://travis-ci.org/SonarOpenCommunity/sonar-cxx/jobs/112379604

**Comment by jmecosta** [comment]
ah ok, tought it was only the class that was broken. in this case then i suppose the problem is related and both can be fixed.

      | file_complexity          | 2.0   |
      | class_complexity         | 4     |
      | violations               | 19    |
      | line_coverage            | 100   |
      | branch_coverage          | 50    |
      | test_failures            | 1     |
      | test_errors              | 0     |
      | tests                    | 2     |
      Assertion Failed: 
      	class_complexity is actually 0.0
      	function_complexity is actually None

at least the class_complexity was changed so something done in this pr has made it 0, perhaps need to wait until the official plugins update this?

**Comment by guwirth** [comment]
add metric COMPLEXITY_IN_CLASSES and COMPLEXITY_IN_FUNCTIONS: should work now with all versions

**Comment by jmecosta** [comment]
Good news :) time for a new release?

**Comment by guwirth** [comment]
ready to review and merge

**Comment by guwirth** [comment]
> new release

@jmecosta there are still some open issues: https://github.com/SonarOpenCommunity/sonar-cxx/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22M+0.9.5%22.
There is also still the erroneous indentation check: fix or remove?

**Comment by jmecosta** [comment]
Disable for now? Perhaps later it will be easier to fix it. We use clang
format, so we are not I'm hurry to validate if code is correctly indented

**Pull request merged**
