### PR TITLE
Feature/it app veyour

### PR DESCRIPTION
**Pull request by jmecosta**
this just enables it in appveyour

### CODE REVIEW

**Comment by guwirth** [comment]
@jmecosta test failed. Not ready for merging?

**Comment by jmecosta** [comment]
nop, its waiting for these to be answered:
https://groups.google.com/forum/#!topic/sonarqube/FN-YWKAG2A4
and 
https://groups.google.com/forum/#!topic/sonarqube/nl8i7-dtHJg

looks to me sonarqube has a bug

**Comment by SonarOpenCommunityAdmin** [comment]
@guwirth has the last #741 change the support for env variables. i finally go the windows it running, however i had to use ${TestDataFolder} and set those as environment variables for the all build.

seems the translation is no longer working

**Comment by SonarOpenCommunityAdmin** [comment]
@guwirth another question, is that there are some tests that might run only on unix environments since they have -Dsonar.include=/usr/include

**Comment by guwirth** [comment]
@jmecosta will have a look and add an integration test

**Comment by jmecosta** [comment]
It's fine to extend the multi module 2 since we have some hard coded paths that need fixing so it can be run in both envs

**Comment by SonarOpenCommunityAdmin** [comment]
@guwirth now its are running in both appveyour and travis,ive include  helper method to skip scenario if  platform is not correct. 

the only issue now is with the ${TestDataFolder} not being translated in the plugin when set via environment variable in travis and appveyour

**Comment by guwirth** [comment]
@jmecosta I have CxxProjectBuilder running again. Which value should `${TestDataFolder}` have? Who is setting it?

```INI
sonar.cxx.cppcheck.reportPath=/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml
```

**Comment by SonarOpenCommunityAdmin** [comment]
in travis is /home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/ and in appveyour TestDataFolder=C:\projects\sonar-cxx\integration-tests\testdata 

those are set in the yml files

  - cmd: SET TestDataFolder=C:\projects\sonar-cxx\integration-tests\testdata

and 

- RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin TestDataFolder=~/sonar-cxx/integration-tests/testdata behave

**Comment by jmecosta** [comment]
in travis is /home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/ and in appveyour TestDataFolder=C:\projects\sonar-cxx\integration-tests\testdata

those are set in the yml files

cmd: SET TestDataFolder=C:\projects\sonar-cxx\integration-tests\testdata
and

RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin TestDataFolder=~/sonar-cxx/integration-tests/testdata behave

when users are running those thye need also set those accordinlgy... we might need to find a better way to handle this, like set it during the test with running path so it works everywhere.

**Comment by jmecosta** [comment]
some findings  with sonarqube 5.3:
- 5.3 does not solve the current issues with using sonar as a service, recent changes made actually makes sonar not to start at all and no relevant error messages are found in logs. -Djava.io.tmpdir= defined in wrapper is now mandatory if we want to start sonarqube using local system account.
- after struggling i tried to actually force the creation C:\WINDOWS\system32\config\systemprofile\AppData\Local\Temp that did no exist and was causing the failures during analysis in first place. this actually works in Appveyour and after applying both java.io.tmpdir and creation of temp folder ive finally was able to run the analysis
- the current workarounds will need to be removed once core is able to properly work under system local account and use properties in the properties file instead of wrapper.

cc @simonbrandhof

**Comment by jmecosta** [comment]
more findings:

- appveyour duration of its are painfully slow, startup of server takes about 4 minutes alone (linux takes less than a minute). 

curios since the compilation and starting the builds is much faster than travis. there must be something weird and its work to investigate this better. probably we require support from appveyour guys

**Comment by jmecosta** [comment]
@guwirth still faling, the expansion is now printed into log however its not used in the report sensor

**Comment by guwirth** [comment]
multi-module project:
* path projectBaseDir must be absolute and not .
* for projectBaseDir it's not possible to use a placeholder because of sonar-runner restriction

**Comment by guwirth** [comment]
And rebase missing?

**Comment by jmecosta** [comment]
It should be rebased!

At least I can see the cxxprojwct builder printing stuff to the log

**Comment by jmecosta** [comment]
ok, seems missed something. i rebase

**Comment by jmecosta** [comment]
the multi module project 1, seems not bother himself by the fact the projectBaseDir is . . passes both on windows and unix so i will leave it like that

**Comment by jmecosta** [comment]
@guwirth yep still fails, i think i had rebase it already.

relevant sutff:

16:08:14.645 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => '/home/travis/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'

16:08:18.202 DEBUG - Using pattern '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' to find reports
16:08:18.203 DEBUG - Unprocessed root directory '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2/A/1/a'
16:08:18.203 DEBUG - Unprocessed report file '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
16:08:18.203 DEBUG - Processed root directory '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2/A/1/a/${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck'
16:08:18.203 DEBUG - Processed report file '*.xml'
16:08:18.210 WARN  - File access Failed '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2/A/1/a/${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck' : 
16:08:18.210 WARN  - Cannot find a report for 'sonar.cxx.cppcheck.reportPath=${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'

https://s3.amazonaws.com/archive.travis-ci.org/jobs/101420428/log.txt

**Comment by guwirth** [comment]
@jmecosta really strange. I did several tests with Windows 7, SQ 5.1.2, slash/backslash, environment variable/-D option, ... it was working.
In this line it should normally already be replaced: `Using pattern '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/.xml' to find reports`

**Comment by jmecosta** [comment]
Did you try to run the it tests with current master and make the change I
did? For me it fails also locally.

**Comment by guwirth** [comment]
@jmecosta have less time this week but will try.

**Comment by jmecosta** [comment]
Ok no prob. This is just for the sake of making sure we have this working
ok for the next release

**Comment by jmecosta** [comment]
@guwirth 

exactly the same as with wrong path. 


10:07:22.913 DEBUG - Using pattern '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' to find reports
10:07:22.913 DEBUG - Unprocessed root directory '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2/A/1/a'
10:07:22.913 DEBUG - Unprocessed report file '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
10:07:22.913 DEBUG - Processed root directory '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2/A/1/a/${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck'
10:07:22.913 DEBUG - Processed report file '*.xml'
10:07:22.922 WARN  - File access Failed '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/cpp-multimodule-project-2/A/1/a/${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck' : 
10:07:22.922 WARN  - Cannot find a report for 'sonar.cxx.cppcheck.reportPath=${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'

ok so it seems the current implementation does not work in multi module since #756 is passing

**Comment by guwirth** [comment]
@jmecosta will have a look what's different with multi-module projects.

**Comment by SonarOpenCommunityAdmin** [comment]
@guwirth ready to review and merge. few things

. the differences in metrics observed in 5.3 ive comment them in the its tests, when we have new LTS than we can enable those again. same for the test density
. windows its are running 5.3 only. seems they take around 9 minutes (3 minutes to start sonar). Travis its around 4 minutes.

**Comment by guwirth** [comment]
@jmecosta thanks for providing this looks good. :+1: 

**cpp-multimodule-project** is commented out? Is this because of placeholder/ multi-module problem?

**Comment by jmecosta** [comment]
@guwirth yes, this is disabled because of the issue we were investigating earlier when environment variables not being properly picked in this kind of multi module approach. i can open a pull request and enable the test back again so you can try to look at it (not sure, but i thought it was the last change made to this that broke it, i tought the first implementation for env variables was working).

**Comment by guwirth** [comment]
@jmecosta would merge this and track remaining issue with #773

**Comment by jmecosta** [comment]
Sounds good

**Pull request merged**
