### PR TITLE
Update LLVM 19 support to 19.1.0 release (first stable release)

### PR DESCRIPTION
**Pull request by opajonk**
* use tag llvmorg-19.1.0
* new ClangTidy rules:
  * boost-use-ranges
  * bugprone-crtp-constructor-accessibility
  * bugprone-pointer-arithmetic-on-polymorphic-object
  * bugprone-return-const-ref-from-parameter
  * bugprone-suspicious-stringview-data-usage
  * cert-ctr56-cpp
  * cert-int09-c
  * clang-analyzer-cplusplus.ArrayDelete
  * clang-analyzer-optin.taint.TaintedAlloc
  * clang-analyzer-security.PutenvStackArray
  * clang-analyzer-security.SetgidSetuidOrder
  * clang-analyzer-unix.BlockInCriticalSection
  * clang-analyzer-unix.Stream
  * linuxkernel-must-check-errs
  * misc-use-internal-linkage
  * modernize-min-max-use-initializer-list
  * modernize-use-designated-initializers
  * modernize-use-ranges
  * modernize-use-std-format
  * readability-enum-initial-value
  * readability-math-missing-parentheses
  * readability-use-std-min-max
  * clang-diagnostic-aarch64-sme-attributes
  * clang-diagnostic-alias-template-in-declaration-name
  * clang-diagnostic-arm-interrupt-vfp-clobber
  * clang-diagnostic-bounds-safety-counted-by-elt-type-unknown-size
  * clang-diagnostic-c++23-attribute-extensions
  * clang-diagnostic-c++23-compat
  * clang-diagnostic-c++2c-compat
  * clang-diagnostic-c2y-extensions
  * clang-diagnostic-cast-function-type-mismatch
  * clang-diagnostic-dangling-assignment
  * clang-diagnostic-dangling-assignment-gsl
  * clang-diagnostic-deprecated-no-relaxed-template-template-args
  * clang-diagnostic-deprecated-ofast
  * clang-diagnostic-explicit-specialization-storage-class
  * clang-diagnostic-extractapi-misuse
  * clang-diagnostic-format-signedness
  * clang-diagnostic-friend-enum
  * clang-diagnostic-function-effects
  * clang-diagnostic-higher-precision-fp
  * clang-diagnostic-hlsl-availability
  * clang-diagnostic-installapi-violation
  * clang-diagnostic-missing-designated-field-initializers
  * clang-diagnostic-missing-include-dirs
  * clang-diagnostic-missing-template-arg-list-after-template-kw
  * clang-diagnostic-mix-packoffset
  * clang-diagnostic-nvcc-compat
  * clang-diagnostic-openacc-deprecated-clause-alias
  * clang-diagnostic-openacc-self-if-potential-conflict
  * clang-diagnostic-pch-vfs-diff
  * clang-diagnostic-pre-c11-compat
  * clang-diagnostic-pre-c11-compat-pedantic
  * clang-diagnostic-pre-c2y-compat
  * clang-diagnostic-pre-c2y-compat-pedantic
  * clang-diagnostic-ptrauth-null-pointers
  * clang-diagnostic-return-mismatch
  * clang-diagnostic-strict-primary-template-shadow
  * clang-diagnostic-template-in-declaration-name
  * clang-diagnostic-tentative-definition-array
  * clang-diagnostic-unsafe-buffer-usage-in-container
* new Clang Static Analyzer rules:
  * cplusplus.ArrayDelete
  * optin.taint.TaintedAlloc
  * security.PutenvStackArray
  * security.SetgidSetuidOrder
  * unix.BlockInCriticalSection
  * unix.Stream
* Added shebangs and executable flags to a few tool scripts
* Updated some old Clang-Tidy rule documentation to newer variants provided by LLVM

Resolves https://github.com/SonarOpenCommunity/sonar-cxx/issues/2778

- - -
This change is [Reviewable](https://reviewable.io/reviews/SonarOpenCommunity/sonar-cxx/2782)

### CODE REVIEW

**Comment by guwirth** [comment]
Hello @opajonk, thanks a lot for providing this update. I will wait for CI results ..

**Comment by opajonk** [comment]
> @opajonk you can download the JAR files from artifacts from here https://github.com/SonarOpenCommunity/sonar-cxx/actions/runs/11387549150

Would it be possible to create a beta-release with this included? Apparently, we have no possibility to install such "snapshots" here...

**Comment by opajonk** [comment]
@guwirth Would it be possible to create a beta-release with this included? Apparently, we have no possibility to install such "snapshots" here...

**Comment by guwirth** [comment]
@opajonk what about using https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/latest-snapshot?

**Comment by opajonk** [comment]
> @opajonk what about using https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/latest-snapshot?

@guwirth For our production SQ-server IT wants to have at least a stable tag...

**Comment by guwirth** [comment]
@opajonk please try with https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.2.0-beta.6

**Pull request merged**
