### PR TITLE
fix #773

### LINKED ISSUE #773: environment variables are not working in multi-module projects
Support environment are not working in multi-module projects:
* leftover from: **Support environment variables and system properties in configuration files** #716

### PR DESCRIPTION
**Pull request by guwirth**

### CODE REVIEW

**Comment by guwirth** [comment]
@jmecosta any idea whats wrong with AppVeyor? It's working with Travis.

**Comment by jmecosta** [comment]
@guwirth must be the env variable we are passing might not be having the correct value. we need to see the log.

can you change this
https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/appveyor.yml#L68

to 

```
  - ps: Get-ChildItem *.log | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
```

so we can get all logs

**Comment by guwirth** [comment]
@jmecosta done

**Comment by jmecosta** [comment]
@guwirth this test can only be run in travis, 

https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/integration-tests/testdata/cpp-multimodule-project-2-reports/reports-cppcheck/cppcheck-result-0.xml#L3

the paths are set for travis only, so we can skip this test in appveyour.

use this: https://github.com/SonarOpenCommunity/sonar-cxx/blob/2ba787e23cb791a414391150fa269b45fa38e454/integration-tests/features/test_execution_statistics.feature#L383

Also now the log shows many times this:
23:45:10.535 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => 'C:\projects\sonar-cxx\integration-tests\testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
23:45:10.535 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => 'C:\projects\sonar-cxx\integration-tests\testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
23:45:10.535 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => 'C:\projects\sonar-cxx\integration-tests\testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
23:45:10.535 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => 'C:\projects\sonar-cxx\integration-tests\testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
23:45:10.550 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => 'C:\projects\sonar-cxx\integration-tests\testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
23:45:10.550 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => 'C:\projects\sonar-cxx\integration-tests\testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'
23:45:10.566 DEBUG - property expansion: key 'sonar.cxx.cppcheck.reportPath'; value '${TestDataFolder}/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml' => 'C:\projects\sonar-cxx\integration-tests\testdata/cpp-multimodule-project-2-reports/reports-cppcheck/*.xml'

Perhaps we dont need the duplicated information or add the reference to the module where the expansion is being done?

**Comment by guwirth** [comment]
@jmecosta thx it's working now.

**Comment by guwirth** [comment]
close #773

**Pull request merged**
