### PR TITLE
refactoring

### PR DESCRIPTION
**Pull request by guwirth**
* unify formatting
* add @todo for deprecated APIs
* add @Override, diamond operator

### CODE REVIEW

**Comment by guwirth** [comment]
@jmecosta & @Bertk is it ok for you to merge this? It's only beautifying.

**Comment by jmecosta** [comment]
Ok

**Comment by Bertk** [comment]
:+1:
I recommend to create a SQ profile which can be used to check the format of the sources. Ideally this can be used within CI but until now we do not have a SQ instance for this. Nevertheless the SQ profile can be used locally to check the updates before a PR is created.

**Comment by jmecosta** [comment]
We can setup the github plugin in appveyour?

**Pull request merged**
