### PR TITLE
use SQ API 6.7

### PR DESCRIPTION
**Pull request by Bertk**
#1272

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1291)

### CODE REVIEW

**Comment by guwirth** [comment]
@Bertk like to release 0.9.8 first. Will shift review after release...

**Comment by Bertk** [comment]
OK. The CI checks are failing and I disabled feature **"Importing Cppcheck ANSI-C reports"** . 

```
      Assertion Failed: error _rest_api_set: http://localhost:9000/api/settings/set -> 400 Client Error:  for url: http://localhost:9000/api/settings/set
```
I declared the header and source file extension as **multivalue** and the syntax of the request changed.

**Comment by guwirth** [comment]
@all someone else wanna review it?

**Comment by Bertk** [comment]
@guwirth Cleanup is still not completed and will be addressed with a another PR.

**Pull request merged**
