### PR TITLE
Close 2302

### LINKED ISSUE #2302: Uppercase file paths in Xunit reports are changed to lowercase.
**Describe the bug**
Our tests sources are located in a subdirectory `<subcomponent>/TESTS/<test_dir>`.
However, the Xunit sensor expects them to be in `<subcomponent>/tests/<test_dir>`
In the end, tests fail to be mapped with their test sources, leading to poor information on the UI.

**Example**:
```xml
<testcase result="fail" name="test_something" filename="somecomponent/TESTS/sometest/tst_something.cpp">
```

In the logs:
```
INFO: Processing xUnit report '/home/jenkins/workspace/.../branch/build/report/test_report_something.xml'
WARN: Cannot find the file '/home/jenkins/workspace/.../branch/somecomponent/tests/sometest/tst_something.cpp' in project 'TestProject' with baseDir '/home/jenkins/workspace/.../branch/', skipping
```

**To Reproduce**
1. Move your tests source to an uppercase directory
2. Set your `sonar.tests` property accordingly
3. Update some tests so that they fail or are skipped 
4. Launch the tests and the SQ analysis
5. Watch the logs to find: `WARN: Cannot find the file '<lower cased path>' in projetc <project> with baseDir ...` 

**Expected behavior**
- No errror in logs.
- The failed tests and their source are shown in the UI

**Desktop:**
 - OS: Linux
 - SonarQube version: 9.2.1.49989
 - cxx plugin version: 2.0.6 (build 2921)
 - sonar-scanner version: 4.6.2.2472-linux
 
**Additional context**
The issue seems to be in cxx-sensors/src/main/java/org/sonar/cxx/sensors/tests/xunit/XunitReportParser.java, line 132: why is the resolved path converted to lower case ? (commit 2c2ecbdee70d095d798fb96c1afd1234e7ff9429)

### PR DESCRIPTION
**Pull request by jnicol31**
Hello,

This pull-request should hopefully close #2302.

Comments are welcome !

Regards.

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/2303)

### CODE REVIEW

**Comment by guwirth** [comment]
@jnicol31 thx looks good.

Only case I have to think about it's case where no filename exists and  test is assigned to TestFile 'global', if behaviour is still the same? Not sure if there is a test for 'global'?

**Comment by jnicol31** [comment]
@guwirth When no filename exists, the `TestFile` was and is still constructed with a `null` parameter. Is it what you call 'global' ? II it is, this case is covered by the unit tests and I did not change the existing behaviour.

**Comment by guwirth** [comment]
@jnicol31 thx yes that is the case I mean. That is the open point I like to verify. Rest looks good!

**Review by guwirth — COMMENTED** [review]
@jnicol31 verified, looks good. Thanks a lot for your contribution!

**Review by guwirth — APPROVED** [review]

**Comment by jnicol31** [comment]
@guwirth You're welcome. Thanks a lot for your support and your responsiveness !

**Pull request merged**
