### PR TITLE
fix CxxLint with unit tests

### PR DESCRIPTION
**Pull request by Bertk**
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1355)

### CODE REVIEW

**Comment by Bertk** [comment]
@guwirth @jmecosta Is this extension still required or can it be removed?

**Comment by jmecosta** [comment]
Yep we are using to do code analysis on the fly in visual studio

**Comment by Bertk** [comment]
@jmecosta OK. The extension uses 
```Java
import org.sonar.api.batch.sensor.internal.SensorContextTester;
...
SensorContextTester sensorContext = SensorContextTester.create(targetFile.getParentFile().toPath()); 
...
sensorContext.fileSystem().add(TestInputFileBuilder.create("", targetFile.getParentFile(), targetFile).build()); 
```
and I feel this should only be used in unit tests. Do you know another way to implement input file context?

**Comment by guwirth** [comment]
@Bertk ready to merge?

**Comment by Bertk** [comment]
@guwirth Yes please 👍

**Pull request merged**
