### PR TITLE
travis.yml: execute automatic HTML checks for rules files

### PR DESCRIPTION
**Pull request by ivangalkin**
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1467)

### CODE REVIEW

**Comment by ivangalkin** [comment]
See below the snipped from [travis log](https://travis-ci.org/SonarOpenCommunity/sonar-cxx/jobs/371279825).

BTW: I realized, that `cxx-sensors/src/main/resources/external/intel_inspector_rules.xml` is not a valid rules file. Is it transformed somehow? What is it good for?

```
$ bash cxx-sensors/src/tools/check_rules.sh
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/clangsa.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/clangtidy.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/compiler-gcc.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/compiler-vc.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/cppcheck.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/drmemory.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/external-rule.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/pclint.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/rats.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/valgrind.xml
[ PASSED ] /home/travis/build/SonarOpenCommunity/sonar-cxx/cxx-sensors/src/main/resources/vera++.xml
The command "bash cxx-sensors/src/tools/check_rules.sh" exited with 0.
```

Done in 8.81s

**Comment by guwirth** [comment]
> I realized, that cxx-sensors/src/main/resources/external/intel_inspector_rules.xml is not a valid rules file. Is it transformed somehow? What is it good for?

@ivangalkin these are (were) the rules for the Intel Inspector and can be used as part of the "other" sensor to handle these issues. Seems no one is using it: you can remove it.

**Comment by ivangalkin** [comment]
@guwirth now I see, there is much infrastructure around such "other" reports, rules, transformations, tests etc. Although `intel_inspector_rules.xml` is not referenced directly, but it looks like (theoretically) somebody could make use of it.

It remembers me a bit on generic coverage or generic test results. So in general the idea is not bad IMHO.

**Comment by guwirth** [comment]
> It remembers me a bit on generic coverage or generic test results. So in general the idea is not bad IMHO.

The generic test and coverage sensors are new in the SQ core, before they were in extra plugins. A generic solution could be to provide a XSLT mechanism outside the sensors (so the current `other` location is not the best place). We have somehow to ensure that XSLT is executed before all sensors. This mechanism could be used for test, covergage, other, ... then

**Comment by guwirth** [comment]
> intel_inspector_rules.xml is not a valid rules file.

@ivangalkin In case the whole file is no more valid I would remove it: not maintained means not used.

**Pull request merged**
