### PR TITLE
use latest sonar runner 2.5.1

### PR DESCRIPTION
**Pull request by guwirth**
http://docs.sonarqube.org/plugins/servlet/mobile#content/view/6954796

### CODE REVIEW

**Comment by guwirth** [comment]
@all: seems to work except reading sonar-runner log. Does someone know what's different with sonar-runner 2.5.1?

```
ut the analysis log contains a line matching
      """
      .*ERROR - Report .* cannot be parsed
      """
      Traceback (most recent call last):
        File "c:\python27\lib\site-packagesehave\model.py", line 1456, in run
          match.run(runner.context)
        File "c:\python27\lib\site-packagesehave\model.py", line 1903, in run
          self.func(context, *args, **kwargs)
        File "integration-tests      eatures\steps	est_execution_statistics.py", line 267, in step_impl
          assert contains_line_matching(context.log, context.text)
      AssertionError
```

**Comment by jmecosta** [comment]
have they change encoding on the files?

**Comment by jmecosta** [comment]
na, some reports are parsed. the google test fails as expected bu with different warnigs supose the tests can be updated also?

**Comment by guwirth** [comment]
**use latest sonar runner 2.5.1**
* warning / errors are different now:
  - old: ERROR - The property 'sonar.tests' is unset. Please set it to proceed
  - new ERROR: The property 'sonar.tests' is unset. Please set it to proceed
* some WARN are INFO only now

@jmecosta are these INFO ok?

**Comment by jmecosta** [comment]
i think so. ERROR: is not us that sets it.

**Pull request merged**
