### PR TITLE
INFO: Undefined report path value for key 'sonar.cxx.other.xslt.1.inputs'

### LINKED ISSUE #1623: INFO: Undefined report path value for key 'sonar.cxx.other.xslt.1.inputs'
Get INFO in V1.2.0:
```
INFO: Undefined report path value for key 'sonar.cxx.other.xslt.1.inputs'
```
In case there are no xslt items in the configuration this info is not needed.

### PR DESCRIPTION
**Pull request by guwirth**
- remove INFO
- re-factor transformFiles
- move tests to right class
- fix #1623

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1628)

### CODE REVIEW

**Comment by guwirth** [comment]
@ivangalkin thx. Looking to the original code there were also this null-checks. But maybe this is only because of wrong unit tests? Will have a look... Original idea was only a small patch and not a whole refactoring...

**Comment by guwirth** [comment]
@ivangalkin tried to make you happy :-). Please have a look....

**Comment by ivangalkin** [comment]
@guwirth thank you for applying of my comments; I am happy now :+1: I've commented on the test, but this is an optional remark.

**Comment by ivangalkin** [comment]
thx :+1:

**Comment by guwirth** [comment]
@ivangalkin thx for your valuable input!

**Pull request merged**
