### PR TITLE
grammar refactoring

### LINKED ISSUE #593: C++ grammar refactoring
Align grammar with latest C++ standard.

e.g. @Bertk By the way, the sequence of the statements within *postfixExpression* is not correct and the definition for ```postfix-expression [ braced-init-list ]```is missing. New parser errors occurred after moving *primary-expression* to the binginning of the rule and I stopped this activity.
Excerpt from N4527 Annex A Grammar summary:
```
postfix-expression:
primary-expression
postfix-expression [ expression ]
postfix-expression [ braced-init-list ]
postfix-expression ( expression-listopt)
simple-type-specifier ( expression-listopt)
typename-specifier ( expression-listopt)
simple-type-specifier braced-init-list
typename-specifier braced-init-list
postfix-expression . templateopt id-expression
postfix-expression -> templateopt id-expression
postfix-expression . pseudo-destructor-name
postfix-expression -> pseudo-destructor-name
postfix-expression ++
postfix-expression --
dynamic_cast < type-id > ( expression )
static_cast < type-id > ( expression )
reinterpret_cast < type-id > ( expression )
const_cast < type-id > ( expression )
typeid ( expression )
typeid ( type-id )
```

### PR DESCRIPTION
**Pull request by guwirth**
5 Statements
- Cleaning this up results in many changes of the checks. Root problem is that there were two rules (ifStatement/switchStatement) instead of one selectionStatement.
- With helper functions asking a selectionStatement if is a 'if or switch' this should be solvable. Changing the grammar to support checks was in my opinion the wrong way.
- IndentationCheck is not filly working anymore

- Expressions: add foldExpression, foldOperator
- Templates: add type-parameter-key
- improve 'Namespace definition'
- improve elaboratedTypeSpecifier
- improve castExpression
- improve using-declaration and using-directive
- add enclosingNamespaceSpecifier test
- add namespaceDefinition test
- add selectionStatement test
- add foldExpression test

- fix for issue #733
- close #593 

ready to review

### CODE REVIEW

**Comment by guwirth** [comment]
Ready to review & merge.
Should all work except IdentationCheck.

**Comment by jmecosta** [comment]
I would like to run a few tests on some of our tests to see the differences. Try to do it during next week

**Comment by jmecosta** [comment]
@guwirth am getting some exception during analysis:

[18:51:41][Step 1/1] 18:51:40.160 DEBUG - finished preprocessing 'E:\prod\structures\src\work\Core\Common\libtools\tool_nullptr_test.cpp'
[18:51:41][Step 1/1] 18:51:40.162 INFO  - Analysis report generated in E:\prod\structures\src\work\Core\Common\.sonar\batch-report
[18:51:41][Step 1/1] INFO: ------------------------------------------------------------------------
[18:51:41][Step 1/1] INFO: EXECUTION FAILURE
[18:51:41][Step 1/1] INFO: ------------------------------------------------------------------------
[18:51:41][Step 1/1] Total time: 3:46.204s
[18:51:41][Step 1/1] ERROR: Error during Sonar runner execution
[18:51:41][Step 1/1] org.sonar.runner.impl.RunnerException: Unable to execute Sonar
[18:51:41][Step 1/1] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
[18:51:41][Step 1/1] 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
[18:51:41][Step 1/1] 	at java.security.AccessController.doPrivileged(Native Method)
[18:51:41][Step 1/1] Final Memory: 70M/573M
[18:51:41][Step 1/1] 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
[18:51:41][Step 1/1] INFO: ------------------------------------------------------------------------
[18:51:41][Step 1/1] 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
[18:51:41][Step 1/1] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
[18:51:41][Step 1/1] 	at org.sonar.runner.api.Runner.execute(Runner.java:90)
[18:51:41][Step 1/1] 	at org.sonar.runner.Main.executeTask(Main.java:70)
[18:51:41][Step 1/1] 	at org.sonar.runner.Main.execute(Main.java:59)
[18:51:41][Step 1/1] 	at org.sonar.runner.Main.main(Main.java:41)
[18:51:41][Step 1/1] Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: E:\prod\structures\src\work\Core\Common\libtools\tool_nullptr_test.cpp
[18:51:41][Step 1/1] 	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
[18:51:41][Step 1/1] 	at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:134)
[18:51:41][Step 1/1] 	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
[18:51:41][Step 1/1] 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
[18:51:41][Step 1/1] 	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:98)
[18:51:41][Step 1/1] 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
[18:51:41][Step 1/1] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
[18:51:41][Step 1/1] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
[18:51:41][Step 1/1] 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:243)
[18:51:41][Step 1/1] 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:238)
[18:51:41][Step 1/1] 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:228)
[18:51:41][Step 1/1] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
[18:51:41][Step 1/1] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
[18:51:41][Step 1/1] 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
[18:51:41][Step 1/1] 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[18:51:41][Step 1/1] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:132)
[18:51:41][Step 1/1] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:117)
[18:51:41][Step 1/1] 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
[18:51:41][Step 1/1] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
[18:51:41][Step 1/1] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
[18:51:41][Step 1/1] 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:45)
[18:51:41][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[18:51:41][Step 1/1] 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[18:51:41][Step 1/1] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[18:51:41][Step 1/1] 	at java.lang.reflect.Method.invoke(Unknown Source)
[18:51:41][Step 1/1] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
[18:51:41][Step 1/1] 	... 9 more
[18:51:41][Step 1/1] Caused by: java.lang.NullPointerException
[18:51:41][Step 1/1] 	at org.sonar.cxx.checks.SwitchLastCaseIsDefaultCheck.getSwitchCases(SwitchLastCaseIsDefaultCheck.java:91)
[18:51:41][Step 1/1] 	at org.sonar.cxx.checks.SwitchLastCaseIsDefaultCheck.visitNode(SwitchLastCaseIsDefaultCheck.java:72)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitNode(AstWalker.java:114)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:85)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visitChildren(AstWalker.java:99)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.visit(AstWalker.java:87)
[18:51:41][Step 1/1] 	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:69)
[18:51:41][Step 1/1] 	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
[18:51:41][Step 1/1] 	... 34 more
[18:51:41][Step 1/1] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
[18:51:41][Step 1/1] Process exited with code 1
[18:51:43][Step 1/1] Step SonarRunner (Command Line) failed

**Comment by jmecosta** [comment]
current master was ok for that file.

**Comment by guwirth** [comment]
@jmecosta thanks for testing  

Don't understand the two messages above: does this mean there are problems or everything is fine?

**Comment by jmecosta** [comment]
The analysis crashes in that rule, the default switch case. If disabling
the rule the analysis goes throw. Now the amount of issues also is bigger
than in previous run. I will check what are the issues that are reported
more

**Comment by guwirth** [comment]
@jmecosta ok thx. Will check SwitchLastCaseIsDefaultCheck again.

**Comment by guwirth** [comment]
@jmecosta issue fixed

**Comment by jmecosta** [comment]
Ok i will confirm today

**Comment by guwirth** [comment]
@Bertk also ok from your side to merge?

**Comment by Bertk** [comment]
@guwirth I noticed a pre-processor issue but this is not related to this PR.
 I am not sure whether this is a regression but I faced issues with variadic macros. Did this work before (https://msdn.microsoft.com/en-us/library/ms177415.aspx)?
I need some more time to check the test results.

**Comment by guwirth** [comment]
@bertk there are some tests https://github.com/SonarOpenCommunity/sonar-cxx/search?utf8=✓&q=__VA_ARGS__. Which case is missing / failing?

**Comment by Bertk** [comment]
@guwirth I just used the sample from msdn with sslr-cxx-toolkit. Sorry, but I noticed this issue in our source code and was pretty sure this work a couple of months ago.

**Pull request merged**
