### PR TITLE
add a single-module integration test example with absolute paths

### PR DESCRIPTION
**Pull request by guwirth**

### CODE REVIEW

**Comment by guwirth** [comment]
@jmecosta this example is working, have to change to
```
- RAILS_ENV=production PATH=$PATH:/tmp/sonar-runner-2.4/bin TestDataFolder=~/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata behave
```

**Comment by jmecosta** [comment]
Ok in travis seems it was the path that is incorrect? I ha e to check in appveyour, seems odd I got both paths incorrectly. I will check.

Regarding this it, perhaps it best to move into a scenario in the import feature?

**Comment by guwirth** [comment]
@jmecosta would merge this to have a sample

**Comment by jmecosta** [comment]
@guwirth but please first rename the project, single module is not correct since its actually with no modules. i will make the change now TestDataFolder=~/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata in my pr to see if it helps

**Comment by guwirth** [comment]
@jmecosta any proposals for the name?
`simple_project_absolute`

**Comment by jmecosta** [comment]
project_import_issues_with_absolution_paths ?

**Pull request merged**
