### PR TITLE
Feature/change language key

### PR DESCRIPTION
**Pull request by jmecosta**
covers #677, now this is working with 5.2

change to 5.2 api its a all different thing and we should not bother with it until actually some of the core plugins update.

also notice, that if a absolute path is used in reports path the lookup fails.

### CODE REVIEW

**Comment by jmecosta** [comment]
@guwirth how can we get logs for the integration tests from travis?

**Comment by guwirth** [comment]
@jmecosta What are the side effects of changing key **c++** to **cxx**?

**Comment by jmecosta** [comment]
Probably to many, at least need to figure out why integration tests fail. For sure profiles need to be patched back into this version . but if we don't so this we definitely will not have a 5.2 compatible version

**Comment by jmecosta** [comment]
Nice at least the ita are running on windows now :) I will take the logs as arrifacts

**Comment by jmecosta** [comment]
@guwirth so made progress in the integration tests, just to find that running sonar as a service does not work properly. anyway we are now able to collect all logs when we have a failed build. at least older versions things should work better in travis. so those are what i found:

1. language=c++ needs to be removed, not a problem since its deprecated.
2. profiles must be restore and patched, that we new already
3. history at the point of transition will show -1000 remove +1000 added issues.

we could wait for 5.3 however we will not be supporting 5.2 at all. anyway we should use some of the things in this pr, at least the integration tests on windows part. also i want to update the python scripts to get the status of the analysis after the local analysis but all versions of sonar dont like to run in windows service so i need to do it locally only.

**Comment by guwirth** [comment]
Hello @jmecosta thanks for testing. 

> history at the point of transition will show -1000 remove +1000 added issues.

Means your are loosing all user defined settings in the database, for example 'false positive'.

**Comment by jmecosta** [comment]
@guwirth ive took the stuff that is important for now, its in appveyour and the support of absolute paths  for reports.

ive build 5.2 and apply the fix from 5.3 and now i can use 0.9.4 in there. so i am not stuck... this can be closed

**Pull request closed without merging**
