### PR TITLE
Fix quality flaws 3

### PR DESCRIPTION
**Pull request by guwirth**
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1611)

### CODE REVIEW

**Comment by ivangalkin** [comment]
@guwirth you've done huge effort converting all for-loops into streams with lambdas. What was the reason for that? In my opinion, the code become more complex, less readable. The new code doesn't use any of stream benefits (declarative/functional approach with maps, filters, collects, distincts, not to mention parallelism). If we want such conversion to be done for the loops, I would prefer more careful approach: rewrite only those loops, where comprehensive `stream()` operation gains some [readability] benefits. Remaining for-loops are perfectly ok to stay just for-loops IMHO .

**Comment by guwirth** [comment]
@ivangalkin thanks for your feedback. In general: I  always try to keep the changes as small as possible and try to follow a pattern.
* most of your proposals can be done in a next PR
* SonarCloud issues: don't have SQ support in NetBeans, so it's try an error.
* will fix isDebugEnabled
* For my understanding stream.forEach is new and more generic way in Java 8. Readability is a matter of taste. Think after reading this several times it's as easy to understand as for-loops?

**Comment by ivangalkin** [comment]
@guwirth w.r.t. to the streams: they have their own benefits and disadvantages. Some more details:

https://blog.jooq.org/2015/12/08/3-reasons-why-you-shouldnt-replace-your-for-loops-by-stream-foreach/
https://stackoverflow.com/questions/44180101/in-java-what-are-the-advantages-of-streams-over-loops

In my opinion your change introduces all the disadvantages of streams without using any possible advantages.

**Comment by guwirth** [comment]
@ivangalkin I integrated most of your hints.
- removed stream()... usage
- removed most isDebugEnabled
- For more detailed samples I had no time. May be you can do it in a PR?

**Pull request merged**
