### PR TITLE
sonar-api-5.6-RC2

### PR DESCRIPTION
**Pull request by guwirth**
- org.codehaus.sonar => org.sonarsource.sonarqube
- use API version 5.6-RC2
- org.sonarsource.dotnet:sonar-dotnet-tests-library:1.3.2
  - support: sonar.cxx.xunit.reportsPaths

### CODE REVIEW

**Comment by guwirth** [comment]
@all someone an idea what's wrong?

```
java.lang.IllegalStateException: Cannot stop.  Current container state was: CONSTRUCTED
	at org.picocontainer.lifecycle.DefaultLifecycleState.stopping(DefaultLifecycleState.java:72) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.stop(DefaultPicoContainer.java:794) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.stop(DefaultPicoContainer.java:799) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.stop(DefaultPicoContainer.java:799) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:166) ~[sonar-core-5.4.jar:na]
	at org.sonar.core.platform.ComponentContainer.stopComponents(ComponentContainer.java:161) ~[sonar-core-5.4.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevel.stop(PlatformLevel.java:93) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.Platform.stopLevel234Containers(Platform.java:238) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.Platform.doStop(Platform.java:267) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.stopQuietly(PlatformServletContextListener.java:59) [sonar-server-5.4.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:52) [sonar-server-5.4.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_71]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_71]
2016.04.21 17:00:18 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.IllegalStateException: Fail to load plugin C++ (Community) [cxx]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:64) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevel4.start(PlatformLevel4.java:729) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.Platform.start(Platform.java:214) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.Platform.startLevel34Containers(Platform.java:188) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:113) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:99) ~[sonar-server-5.4.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:44) ~[sonar-server-5.4.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_71]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_71]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_71]
Caused by: java.lang.NoClassDefFoundError: com/google/common/collect/ImmutableList
	at org.sonar.plugins.cxx.CxxPlugin.generalProperties(CxxPlugin.java:78) ~[na:na]
	at org.sonar.plugins.cxx.CxxPlugin.getExtensions(CxxPlugin.java:448) ~[na:na]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:55) ~[sonar-server-5.4.jar:na]
	... 15 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39) ~[sonar-classloader-1.0.jar:na]
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87) ~[sonar-classloader-1.0.jar:na]
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76) ~[sonar-classloader-1.0.jar:na]
	... 18 common frames omitted
```

**Comment by jmecosta** [comment]
some dep missing in pom?

like:
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.4</version>
    </dependency>

at least i dont see anything obvious on the csharp plugin, that also include the test library

**Comment by guwirth** [comment]
Problem is:
```
java.lang.ClassNotFoundException: com.google.common.collect.ImmutableList
    at org.sonar.plugins.cxx.CxxPlugin.generalProperties(CxxPlugin.java:78) ~[na:na]
    at org.sonar.plugins.cxx.CxxPlugin.getExtensions(CxxPlugin.java:448) ~[na:na]
```
Is this still needed or possible to replace somehow with Java 8?

**Comment by jmecosta** [comment]
does this help
http://stackoverflow.com/questions/35369058/custom-plugin-for-sonarqube-5-2-produces-noclassdeffounderror

**Comment by guwirth** [comment]
@all I played around an evening but I'm not able to resolve the dependency conflicts. I stop this until other plugins are also upgrading to a newer API.

**But help is welcome.** If someone is more familiar with dependencies/POM I would be happy if someone can fix this.

**Comment by jmecosta** [comment]
@guwirth i think we need ot update the property definition, we are using 

```
    return ImmutableList.of(
      PropertyDefinition.builder(SOURCE_FILE_SUFFIXES_KEY)
      .defaultValue(CxxLanguage.DEFAULT_SOURCE_SUFFIXES)
      .name("Source files suffixes")
      .description("Comma-separated list of suffixes for source files to analyze. Leave empty to use the default.")
      .subCategory(subcateg)
      .onQualifiers(Qualifiers.PROJECT, Qualifiers.MODULE)
      .index(1)
      .build(),
```

that causes the exception, other plugins use
```
@Properties({
  @Property(
    key = CSharpPlugin.FILE_SUFFIXES_KEY,
    defaultValue = CSharpPlugin.FILE_SUFFIXES_DEFVALUE,
    name = "File suffixes",
    description = "Comma-separated list of suffixes of files to analyze.",
    project = true, global = true
  ),
  @Property(
    key = CSharpPlugin.IGNORE_HEADER_COMMENTS,
    defaultValue = "true",
    name = "Ignore header comments",
    description = "If set to \"true\", the file headers (that are usually the same on each file: " +
      "licensing information for example) are not considered as comments. Thus metrics such as \"Comment lines\" " +
      "do not get incremented. If set to \"false\", those file headers are considered as comments and metrics such as " +
      "\"Comment lines\" get incremented.",
    project = true, global = true,
    type = PropertyType.BOOLEAN)
})
```

we might need to migrate all those

**Comment by jmecosta** [comment]
doing this
```
      List<PropertyDefinition> data = new ArrayList<>();
    String subcateg = "(3) Testing & Coverage";
    data.add(
```
also makes it pass, then you need to merge https://github.com/SonarOpenCommunity/sonar-cxx/pull/833/commits to get ride of problems with new sqale model in 5.5

and now the new class not found is:

2016.04.23 13:53:46 ERROR web[o.a.c.c.C.[.[.[/]] Exception sending context initialized event to listener instance of class org.sonar.server.platform.PlatformServletContextListener
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at org.sonar.plugins.cxx.utils.CxxAbstractRuleRepository.define(CxxAbstractRuleRepository.java:79) ~[na:na]
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:54) ~[sonar-server-5.5-RC1.jar:na]
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:97) ~[sonar-server-5.5-RC1.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_77]

**Comment by jmecosta** [comment]
ok, after diffing a bit more i think we need to wait for a new version of the sslr as far as i can see.

guava versions are imcopatible

in sslr 10.0.1 compatible with 4.5.5
```
https://github.com/SonarSource/sslr/blob/master/pom.xml#L127
```

in 5.4
```
https://github.com/SonarSource/sonarqube/blob/branch-5.4/pom.xml#L602
```

if you upgrade the guava to 17.0 in cxx plugin than tests explod.

**Comment by guwirth** [comment]
```
Caused by: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Lcom/google/common/collect/ImmutableList;
	at org.sonar.plugins.cxx.CxxPlugin.codeAnalysisProperties(CxxPlugin.java:147) ~[na:na]
	at org.sonar.plugins.cxx.CxxPlugin.getExtensions(CxxPlugin.java:438) ~[na:na]
	at org.sonar.api.SonarPlugin.define(SonarPlugin.java:49) ~[sonar-plugin-api-5.5.jar:na]
	at org.sonar.server.plugins.ServerExtensionInstaller.installExtensions(ServerExtensionInstaller.java:64) ~[sonar-server-5.5.jar:na]
```

**Comment by guwirth** [comment]
@all Still not working there seems too be a problem in CxxRuleRepository? Do we have to switch to org.sonar.api.server.rule.RulesDefinitionAnnotationLoader?

```
java.lang.NoClassDefFoundError: org/apache/commons/lang/StringUtils
	at org.sonar.squidbridge.annotations.AnnotationBasedRulesDefinition.newRule(AnnotationBasedRulesDefinition.java:120) ~[na:na]
	at org.sonar.squidbridge.annotations.AnnotationBasedRulesDefinition.addRuleClasses(AnnotationBasedRulesDefinition.java:93) ~[na:na]
	at org.sonar.squidbridge.annotations.AnnotationBasedRulesDefinition.addRuleClasses(AnnotationBasedRulesDefinition.java:86) ~[na:na]
	at org.sonar.squidbridge.annotations.AnnotationBasedRulesDefinition.load(AnnotationBasedRulesDefinition.java:75) ~[na:na]
	at org.sonar.plugins.cxx.CxxRuleRepository.define(CxxRuleRepository.java:36) ~[na:na]
	at org.sonar.server.rule.RuleDefinitionsLoader.load(RuleDefinitionsLoader.java:54) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.rule.RegisterRules.start(RegisterRules.java:97) ~[sonar-server-5.5.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.invokeMethod(ReflectionLifecycleStrategy.java:110) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.lifecycle.ReflectionLifecycleStrategy.start(ReflectionLifecycleStrategy.java:89) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer$1.start(ComponentContainer.java:320) ~[sonar-core-5.5.jar:na]
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.behaviors.Stored.start(Stored.java:110) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009) ~[picocontainer-2.15.jar:na]
	at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767) ~[picocontainer-2.15.jar:na]
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141) ~[sonar-core-5.5.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:84) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:44) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:78) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:44) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:75) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.platform.Platform.executeStartupTasks(Platform.java:199) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:114) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.platform.Platform.doStart(Platform.java:99) ~[sonar-server-5.5.jar:na]
	at org.sonar.server.platform.PlatformServletContextListener.contextInitialized(PlatformServletContextListener.java:44) ~[sonar-server-5.5.jar:na]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4812) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5255) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398) [tomcat-embed-core-8.0.30.jar:8.0.30]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_66]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_66]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang.StringUtils
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39) ~[sonar-classloader-1.0.jar:na]
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87) ~[sonar-classloader-1.0.jar:na]
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76) ~[sonar-classloader-1.0.jar:na]
	... 40 common frames omitted
```

**Comment by jmecosta** [comment]
@guwirth see: https://groups.google.com/forum/#!topic/sonarqube/Is7lGzPCETI it a risk to start touching any apis at the moment. seems there are plenty of stuff comming out and in in 5.x versions so we run into risk of actually braking the cxx pluging. 

IMO we should wait for 5.6 LTS and then proceed with this, support for 5.5 shoudl be possible with the current depreacted apis

**Comment by guwirth** [comment]
@jmecosta thx for the hint. Will stop this until SQ 5.6 is available.

**Comment by guwirth** [comment]
First version working with SQ 5.6 LTS API :+1:

**Comment by jmecosta** [comment]
Does this means that they did not remove the deprecated stuff and there are
still multiple ways of doing some thing? Supose guava is still a problem.?

**Comment by guwirth** [comment]
@jmecosta that's all a little bit strange at the moment:
* SQ 5.6 RC2 is available for testing
* SQ 5.6 RC2 **API** is available but no other plugin is using it yet. They are all still on 4.5.x (see POM files of Java, Javascript and CSharp). Don't know when they are planning to upgrade?
* We are using 5.6 SQ and API now and all deprecated APIs seems still to work? Build works, Unit Tests work, Integration Tests work.
* I did no manual tests with SQ 5.6 yet. Looking forward to get feedback from others...

**Comment by jmecosta** [comment]
sure no problem. i will put the 5.6 in test server and try it.

**Pull request merged**
