### PR TITLE
change base to gap

### PR DESCRIPTION
**Pull request by jmecosta**
should handle startup issues in 5.5

### CODE REVIEW

**Comment by jmecosta** [comment]
@Bertk supose you can review this one?

**Comment by Bertk** [comment]
:+1: Please also update the XML schema (https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/rules.xsd). We can use the schema to enforce a ordered sequence which helps to review updates of rules.
Shouldn't we remove the old definitions [cxx-model.xml](https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/sonar-cxx-plugin/src/main/resources/com/sonar/sqale/cxx-model.xml). I think the this is not supported anymore [SONAR-7364](https://jira.sonarsource.com/browse/SONAR-7364) and [MMF-185](https://jira.sonarsource.com/browse/MMF-185)

**Comment by jmecosta** [comment]
@Bertk the xsd is still valid, there was only remediationFunctionBaseEffort -> remediationFunctionGapMultiplier. Are all the rules.xml updated from cxx-model ? if so i can remove it in this pr

**Comment by Bertk** [comment]
@jmecosta I think we should keep the cxx-model.xml because we will loose the sub-characteristic and for SQALE users this might be a problem. The plug-in should come with a default definition for SQALE but the documentation **How to ...** is not available :unamused: (see also https://github.com/SonarSource/sonarqube/blob/branch-5.5/server/sonar-server/src/main/resources/com/sonar/sqale/technical-debt-model.xml)
I am also not sure whether we can remove redundant parts like the remediation definitions from cxx-model.xml:
```xml        
        <prop>
          <key>remediationFunction</key>
          <txt>LINEAR</txt>
        </prop>
        <prop>
          <key>remediationFactor</key>
          <val>15</val>
          <txt>min</txt>
        </prop>
```
These settings are available for all C++ rule repositories except the _common-c++_ (sonar-common) rules which are not available in a tool rule repository.

**Comment by Bertk** [comment]
@jmecosta Just saw this commit [SONAR-7364 Remove SQALE characteristics from measures and rules](https://github.com/SonarSource/sonarqube/commit/d88d443bbe5c5dabe45b44760108fa7b506cd7d9) and the sub-characteristic are useless with SQ 5.5 and later.

**Comment by jmecosta** [comment]
@Bertk right, then i will remove the model.

**Comment by guwirth** [comment]
@all please have also a look to this https://github.com/SonarOpenCommunity/sonar-cxx/issues/720.

**Comment by Bertk** [comment]
@all It is time to merge this PR since SQ 5.5 is released but the last commit is not complete. The unit tests etc. need some updates as well (see acf0df62bdcc7e2dff64d4e32f0353133191d7a1).

**Comment by guwirth** [comment]
@all any idea what the problem is?

Tests in error: 
  CxxExternalRuleRepositoryTest.createNonEmptyRulesTest:109 » IllegalArgument re...
  CxxExternalRuleRepositoryTest.verifyRuleValuesTest:138 » IllegalArgument resou...
  CxxExternalRuleRepositoryTest.createNullRulesTest:123 » IllegalArgument resour...
  CxxExternalRuleRepositoryTest.verifyTemplateRuleIsFound:95 » IllegalArgument r...
  CxxRuleRepositoryTest.rulesTest:34 » IllegalArgument resource /com/sonar/sqale...
  CxxPCLintRuleRepositoryTest.createRulesTest:40 » IllegalArgument resource /com...
  CxxRatsRuleRepositoryTest.createRulesTest:39 » IllegalArgument resource /com/s...
  CxxCompilerRuleRepositoryTest.createGccRulesTest:53 » IllegalArgument resource...
  CxxCompilerRuleRepositoryTest.createVcRulesTest:40 » IllegalArgument resource ...
  CxxCppCheckRuleRepositoryTest.createRulesTest:39 » IllegalArgument resource /c...
  CxxValgrindRuleRepositoryTest.containsValidFormatInExtensionRulesNewFormat:70 » IllegalArgument
  CxxValgrindRuleRepositoryTest.shouldContainProperNumberOfRules:42 » IllegalArgument
  CxxValgrindRuleRepositoryTest.containsEmptyExtensionRulesFile:98 » IllegalArgument
  CxxValgrindRuleRepositoryTest.containsValidFormatInExtensionRulesOldFormat:56 » IllegalArgument
  CxxValgrindRuleRepositoryTest.containsInvalidFormatInExtensionRulesNewFormat:84 » IllegalArgument
  CxxVeraxxRuleRepositoryTest.createRulesTest:40 » IllegalArgument resource /com...

**Comment by Bertk** [comment]
@guwirth Sorry my last comment was not perfect and with this commit it works (https://github.com/Bertk/sonar-cxx/commit/acf0df62bdcc7e2dff64d4e32f0353133191d7a1)

**Comment by guwirth** [comment]
@Bertk looks good. Please provide PR would merge it. With SQALE values we have to check how to set it for **other**. There is also #720. But to be honest, I lost a little bit the overview which APIs are still valid / supported for SQALE. But that could be done in another PR.

**Pull request closed without merging**
