### PR TITLE
LLVM 19.0.0 support for SQ-10

### PR DESCRIPTION
**Pull request by opajonk**
Forward-ported ea53cede to SQ-10 branch

- - -
This change is [Reviewable](https://reviewable.io/reviews/SonarOpenCommunity/sonar-cxx/2706)

### CODE REVIEW

**Comment by guwirth** [comment]
@opajonk thx for providing this.

**Comment by guwirth** [comment]
Hi @opajonk,

on this page you can download the JAR files
* https://github.com/SonarOpenCommunity/sonar-cxx/actions/runs/10315131155
   * https://github.com/SonarOpenCommunity/sonar-cxx/actions/runs/10315131155/artifacts/1794702187

Regards,

**Comment by opajonk** [comment]
Installed it on our SQ-10 server, works as expected!

**Comment by guwirth** [comment]
Hi @opajonk, I created a beta3: https://github.com/SonarOpenCommunity/sonar-cxx/releases/tag/cxx-2.2.0-beta.3

**Pull request closed without merging**
