### PR TITLE
deprecate *PUBLIC*API* metrics

### PR DESCRIPTION
**Pull request by ivangalkin**
* `PUBLIC_API`, `PUBLIC_UNDOCUMENTED_API` and `PUBLIC_DOCUMENTED_API_DENSITY`
  were depricated since SQ 6.2 (https://jira.sonarsource.com/browse/SONAR-8328)
  but existed as custom sonar-cxx metrics

* the minimal supported SQ version now is 6.7

* moreover, it looks like there is a general problem in displaying
  custom metrics (see #1509)

* that means that nobody a) expects that the SQ plugin implements the
  deprectad metrics and b) nobody misses them (because they are just not
  visualized)

* BTW public API measurements belong to the obligatory AST Visitors
  and introduce the time overhead of ~6% (measured with #1507,
  6% means, that if there is no sensors activated at all
  the importing of C++ project will still cause a calculation
  of a bunch of metrics; summary overhead of this calculation
  considered as 100%)

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1510)

### CODE REVIEW

**Comment by ivangalkin** [comment]
`AbstractCxxPublicApiVisitor` and the corresponding tests `CxxPublicApiVisitorTest` (must be renamed) can be moved from `cxx-squid` to `cxx-checks` too. If there will be general agreement w.r.t. this PR, I will update the change. Please review.

**Comment by guwirth** [comment]
Hi @ivangalkin, there was by intention a custom metric introduced. Think there is much value to detect undocumented public API. This is for sure technical debt. Never understood why SonarSource removed it? What’s correct: if someone don’t use it he should not pay for it. Maybe we can check if rule i s active. Regards,

**Comment by guwirth** [comment]
Alternativ would be #1062

**Comment by ivangalkin** [comment]
will be abandoned as soon as #1509 is finished

**Comment by ivangalkin** [comment]
abandon in favor of #1514

**Pull request closed without merging**
