### PR TITLE
implement recovery for issues

### PR DESCRIPTION
**Pull request by jmecosta**
finish #758

### CODE REVIEW

**Comment by guwirth** [comment]
@jmecosta checks failing

**Comment by jmecosta** [comment]
One of the import reports it test is failing g. I will check tonight

**Comment by jmecosta** [comment]
@guwirth test should be fixed now, however the builds are not running? do you know anything about it

**Comment by jmecosta** [comment]
took a bit of time, but its building

**Comment by guwirth** [comment]
Hi @jmecosta, except this
```
 .*WARN.*The report '.*' seems to be empty, ignoring.
.*ERROR.*The report '.*' seems to be empty.
```
it looks good to me. Thx for providing this.

Regards,

**Comment by jmecosta** [comment]
Yep I will revert that, just seem logic at that time.

**Comment by jmecosta** [comment]
@guwirth should be ok now

**Pull request merged**
