### PR TITLE
Cleanup Travis integration test

### PR DESCRIPTION
**Pull request by guwirth**
- add SQ6.4 to Travis
- use new rest api /api/qualityprofiles/search
- cleanup integration test Pyhton scripts

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1148)

### CODE REVIEW

**Comment by guwirth** [comment]
@all tried to bring our integration tests with SQ 6.4 into operation. They are always hanging at the beginning (see log files of Travis). Someone an idea what's different with 6.4?

**Comment by jmecosta** [comment]
can we export the sonar log? seems that sq is not starting

**Comment by guwirth** [comment]
There is a build timeout because there are 10 min no outputs. In this case Travis is not calling 'on failure' . So think if we won't see the log file we have to add it to our script. Can try it this evening...

**Comment by guwirth** [comment]
@all I added some more logging and was able to narrow it down to `_runCommand`:

In good case it looks like this:
```
When I run sonar-scanner with following options
 _runCommand begin
 context.log:_coverage_project_.log
 sonarhome:/tmp/sonarqube-6.3.1
 context.serverlog:/tmp/sonarqube-6.3.1/logs/sonar.log
 projecthome:/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project
 _runCommand end
```

And with 6.4 **(never reach end**):
```
When I run sonar-scanner with following options
_runCommand begin
 context.log:_coverage_project_.log
 sonarhome:/tmp/sonarqube-6.4-RC3
 context.serverlog:/tmp/sonarqube-6.4-RC3/logs/sonar.log
 projecthome:/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project
```
Seems to hang in:
https://github.com/guwirth/sonar-cxx/blob/4216a4643d717c2d096052ad818d796a4e77bfec/integration-tests/features/steps/test_execution_statistics.py#L336

**Any ideas?**

**Comment by guwirth** [comment]
To see what's going on I removed the redirection of the sonar-scanner output to file. Output is:
```
INFO: SonarQube Scanner 2.8
INFO: Java 1.8.0_121 Oracle Corporation (64-bit)
INFO: Linux 3.13.0-115-generic amd64
INFO: User cache: /home/travis/.sonar/cache
INFO: Load global settings
INFO: Load global settings (done) | time=223ms
INFO: User cache: /home/travis/.sonar/cache
INFO: Load plugins index
INFO: Load plugins index (done) | time=23ms
INFO: Download sonar-cxx-plugin-0.9.8-SNAPSHOT.jar
INFO: Download sonar-python-plugin-1.7.0.1195.jar
INFO: Download sonar-csharp-plugin-5.10.1.1411.jar
INFO: Download sonar-c-plugin-0.9.8-SNAPSHOT.jar
INFO: Download sonar-java-plugin-4.9.0.9858.jar
INFO: Download sonar-flex-plugin-2.3.jar
INFO: Download sonar-xml-plugin-1.4.2.885.jar
INFO: Download sonar-scm-git-plugin-1.2.jar
INFO: Download sonar-php-plugin-2.10.0.2087.jar
INFO: Download sonar-scm-svn-plugin-1.4.0.522.jar
INFO: Download sonar-javascript-plugin-3.0.0.4962.jar
INFO: SonarQube server 6.4.0
INFO: Default locale: "en_US", source code encoding: "UTF-8" (analysis is platform dependent)
INFO: Process project properties
INFO: Load project repositories
INFO: Load project repositories (done) | time=24ms
INFO: Execute project builders
INFO: Execute project builders (done) | time=4ms
INFO: Load quality profiles
INFO: Load quality profiles (done) | time=90ms
INFO: Load active rules
INFO: Load active rules (done) | time=6861ms
INFO: Load metrics repository
INFO: Load metrics repository (done) | time=168ms
INFO: Publish mode
INFO: Project key: coverage_project
INFO: -------------  Scan coverage_project
INFO: Load server rules
INFO: Load server rules (done) | time=3477ms
INFO: Language is forced to c++
INFO: Initializer GenericCoverageSensor
INFO: Initializer GenericCoverageSensor (done) | time=0ms
INFO: Base dir: /home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project
INFO: Working dir: /home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/.sonar
INFO: Source paths: src
INFO: Source encoding: UTF-8, default locale: en_US
INFO: Index files
WARN: File '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/src/Makefile' is ignored because it doesn't belong to the forced language 'c++'
INFO: 7 files indexed
INFO: Quality profile for c++: Sonar way
INFO: Sensor c++ SquidSensor [cxx]
WARN: [/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/src/component1.cc:1]: cannot find the sources for '#include <iostream>'
WARN: [/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/src/component2.cc:1]: cannot find the sources for '#include <iostream>'
WARN: [/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/src/integration_test.cc:1]: cannot find the sources for '#include <iostream>'
WARN: [/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/src/main.cc:1]: cannot find the sources for '#include <iostream>'
WARN: [/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/src/unit_test.cc:1]: cannot find the sources for '#include <iostream>'
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Added report '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/ut-coverage.xml' (parsed by: CoberturaParser) to the coverage data
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Added report '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/it-coverage.xml' (parsed by: CoberturaParser) to the coverage data
INFO: Scanner found '1' report files
INFO: Parser will parse '1' report files
INFO: Added report '/home/travis/build/SonarOpenCommunity/sonar-cxx/integration-tests/testdata/coverage_project/overall-coverage.xml' (parsed by: CoberturaParser) to the coverage data

Exception in thread "main" java.lang.NoClassDefFoundError: org/sonar/graph/DirectedGraphAccessor
	at org.sonar.cxx.sensors.squid.CxxSquidSensor.save(CxxSquidSensor.java:226)
	at org.sonar.cxx.sensors.squid.CxxSquidSensor.execute(CxxSquidSensor.java:188)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:87)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:81)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:67)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:75)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.ClassNotFoundException: org.sonar.graph.DirectedGraphAccessor
	at org.sonar.classloader.ParentFirstStrategy.loadClass(ParentFirstStrategy.java:39)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:87)
	at org.sonar.classloader.ClassRealm.loadClass(ClassRealm.java:76)
	... 33 more
```

**Pull request merged**
