### PR TITLE
parse Clang Static Analyzer plist reports

### LINKED ISSUE #547: Integrate Clang Static Analyzer
The Clang Static Analyzer is a source code analysis tool that finds bugs in C, C++, and Objective-C programs (http://clang-analyzer.llvm.org). 

Support this tool like Cppcheck.

### PR DESCRIPTION
**Pull request by gyorb**
Add support to parse Clang Static Analyzer plist results:
* reports can be parsed from v3.7 and up (checker name is available since that version in the plist reports)
* rules list is generated based on Clang v4.0.
* simple unit tests are added

Resolves #547

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1161)

### CODE REVIEW

**Comment by guwirth** [comment]
@gyorb thanks for your contribution. We will review it...

**Comment by guwirth** [comment]
@wichtounet think that's the feature you were looking for. Maybe you have also some time to try it out...

**Comment by wichtounet** [comment]
Hi, 

Thanks for this contribution :+1: 

I just installed this on my sonar instance and try to test it. But I seen one big problem. Unless I'm mistaken, you have to set the path of **a single plist file**, right ? How do you to handle the use of scan-build ? scan-build generates a set of plist files in a folder. 

If you don't plan to support scan-build, could you tell me how to use the static-analyzer with several threads? 

Thanks :)

**Comment by gyorb** [comment]
Hi,

I've tested the plugin with scan-build and it can parse multiple plist files. The trick is to configure an ant-style glob pattern as a reportPath like this:
`sonar.cxx.clangsa.reportPath=clang_reports/scan-build-2017-06-09-16-20-04-481327/*.plist`

I've used [this](https://github.com/rizsotto/scan-build) scan-build and Clang v3.8 for testing.

I wanted to create a wiki section on how to analyze a project and import the results, after the new feature is accepted.

I found a [SampleProject2](https://github.com/SonarOpenCommunity/sonar-cxx/tree/c262545e002462fbd749daa050e119a646cd9f88/sonar-cxx-plugin/src/samples/SampleProject2) should I update the documentation there too?

**Comment by wichtounet** [comment]
Ok, perfect. I didn't think of trying that. I used: 

`sonar.cxx.clangsa.reportPath=tmp/*/*.plist`

And it worked well. 

It had to force alpha checkers to find issues in my programs. The analysis worked fine and the three warnings from the clang-static-analyzer were correctly reported in Sonar. 

For me, it seems to work quite well. I don't have projects with lots of violations of static-analyzer, so cannot really test with large number of errors .

**Comment by guwirth** [comment]
integration test:
* sample project should be here https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/testdata
   * clangsa_project
* script should be here: https://github.com/SonarOpenCommunity/sonar-cxx/tree/master/integration-tests/features
   * importing_clangsa_reports.feature
* use cppcheck as sample: https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/integration-tests/features/importing_cppcheck_reports.feature

**Comment by guwirth** [comment]
@gyorb do you work on integration test or should we merge it as is?

**Comment by gyorb** [comment]
@guwirth I had some other things to do and I did not finish the integration tests yet. I hope I can finish them soon.

**Comment by guwirth** [comment]
@gyorb I merge this so other has the chance to try it.

**Comment by gyorb** [comment]
> @gyorb looks good to me. Think two additional things are missing:
>  * add documentation in wiki
>  * add an integration sample

@guwirth thanks for the review. I've added the integration tests in pr #1172  and extended the wiki about the analysis [here](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers#clang-static-analyzer) and about the configuration [here](https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Supported-configuration-properties#sonarcxxclangsareportpath).

**Comment by guwirth** [comment]
@gyorb thx for providing detailed documentation how to use the feature.

**Pull request merged**
