### PR TITLE
Make FileRegularExpressionCheck more stable, close #371

### LINKED ISSUE #371: java.nio.charset.MalformedInputException in FileRegularExpressionCheck.java:120
I activated the FileRegularExpressionCheck for checking includes of stdafx.h in other header files but the analysis fails after some time. Looks like the encoding for the source files (*sonar.sourceEncoding*) is not handled in FileRegularExpressionCheck.java and the exception is not handled as well.
The analysis with sonar_runner fails:
```
ERROR: Error during Sonar runner execution
ERROR: Unable to execute Sonar
ERROR: Caused by: Unable to analyze file: C:\TFS_Server\Server\some-folder\some-header.h
ERROR: Caused by: java.nio.charset.MalformedInputException: Input length = 1
ERROR: Caused by: Input length = 1
``` 
The debug output has the details:
```
org.sonar.runner.impl.RunnerException: Unable to execute Sonar
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
        at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
        at java.security.AccessController.doPrivileged(Native Method)
        at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
        at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
        at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
        at org.sonar.runner.api.Runner.execute(Runner.java:100)
        at org.sonar.runner.Main.executeTask(Main.java:70)
        at org.sonar.runner.Main.execute(Main.java:59)
        at org.sonar.runner.Main.main(Main.java:53)
Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: C:\TFS_Server\Server\some-folder\some-header.h
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:127)
        at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:112)
        at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:79)
        at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:70)
        at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:119)
        at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:194)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:233)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:228)
        at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:226)
        at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:221)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.scan.ScanTask.scan(ScanTask.java:64)
        at org.sonar.batch.scan.ScanTask.execute(ScanTask.java:51)
        at org.sonar.batch.bootstrap.TaskContainer.doAfterStart(TaskContainer.java:125)
        at org.sonar.api.platform.ComponentContainer.startComponents(ComponentContainer.java:92)
        at org.sonar.api.platform.ComponentContainer.execute(ComponentContainer.java:77)
        at org.sonar.batch.bootstrap.BootstrapContainer.executeTask(BootstrapContainer.java:173)
        at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:95)
        at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
        at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
        ... 9 more
Caused by: org.sonar.api.utils.SonarException: java.nio.charset.MalformedInputException: Input length = 1
        at org.sonar.cxx.checks.FileRegularExpressionCheck.visitFile(FileRegularExpressionCheck.java:100)
        at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:67)
        at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:106)
        ... 36 more
Caused by: java.nio.charset.MalformedInputException: Input length = 1
        at java.nio.charset.CoderResult.throwException(CoderResult.java:277)
        at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:798)
        at org.sonar.cxx.checks.FileRegularExpressionCheck.fromFile(FileRegularExpressionCheck.java:120)
        at org.sonar.cxx.checks.FileRegularExpressionCheck.visitFile(FileRegularExpressionCheck.java:95)
        ... 38 more
```

### PR DESCRIPTION
**Pull request by guwirth**
close #371

### CODE REVIEW

**Comment by wenns** [comment]
Im missing a test which triggers #371... Wasnt doable?

**Comment by guwirth** [comment]
What is this doing in a check?
Throwing an exception and break the analysis or
create only an error message and continue?

      } catch (IOException e) {
        throw new SonarException(e);
      }

**Comment by wenns** [comment]
I think it'll break the analysis. The plugin related stack begins in this case with CxxSquidSensor.analyse(). I dont see any catches in there. You can try it out by throwing the exception unconditionally.

**Comment by guwirth** [comment]
I'm still not a Java and SQ expert. For this check I did a copy and had a look to other checks. They all do it this way. If this is a problem with FileRegularExpressionCheck and we expect that checks continue after such a bug we have to change it in all checks.

**Comment by guwirth** [comment]
- set CodingErrorAction.REPLACE for decode …
- catch exceptions
- move CharsetDecoder to init
- add additional test case
- close #371

**Pull request merged**
