### PR TITLE
improve executable lines code metric

### PR DESCRIPTION
**Pull request by Bertk**
- use AST to identify executable lines (SQ 6.2 and newer versions)
- still experimental (some AST nodes of CxxGrammarImpl might be missing)
#1203

---
This change is [Reviewable](https://reviewable.io/reviews/sonaropencommunity/sonar-cxx/1206)

### CODE REVIEW

**Comment by guwirth** [comment]
Hi @Bertk,

I played around with our code base and found the following points:

* **case/default are not marked:**
coverage3

* **if / else: else is not marked**
coverage2

* **try / catch: catch not marked:**
coverage7

* **differences old / new:**
old:
coverage6
new:
coverage7
old:
coverage5
new:
coverage4

Wondering if { } should not be ignored in general. Is not really 'executable code'?

Regards,

**Comment by guwirth** [comment]
Hi @Bertk,

second proposal for an improvement. Like the construct with **forEach** to set the metric like here:
https://github.com/SonarSource/sonar-javascript/blob/7df6fc71b6f481dce2739843db3e2e8e5a908efc/javascript-frontend/src/main/java/org/sonar/javascript/metrics/MetricsVisitor.java#L173

Regards,

**Comment by guwirth** [comment]
@Bertk 
Also some hints I found:
* Things that are executable: https://docs.sonarqube.org/display/DEV/Executable+Lines
* [MMF-739](https://jira.sonarsource.com/browse/MMF-739)
* [EXECUTABLE_LINES_DATA](http://javadocs.sonarsource.org/latest/apidocs/index.html?org/sonar/api/measures/CoreMetrics.html): Information about executable lines of code in file. Key-value pairs, where key - is a number of line, and value - is an indicator of whether line contains executable code (1) or not (0). If a line number is missing in the map it is equivalent to the default value (0).

**Comment by guwirth** [comment]
@Bertk ... and by the way: thanks a lot for spending your time!

**Comment by Bertk** [comment]
@guwirth I am still waiting on an analysis on our code base. Thanks for the hints - the rule only to consider the first line of a multi-line statement is interesting and make the solution more complex. I check this details on the weekend.
The handling of punctuation seems to be different with the Microsoft VS way ("{","}"). I want to have the same UI experience for the developers as they know from their preferred IDE and maybe a configuration item could help.

**Comment by guwirth** [comment]
Hello @Bertk,

would extend the unit test with the file https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-sensors/src/test/resources/org/sonar/cxx/sensors/ncloc.cc with the following cases:

```C++
void func7(bool flag)
{
    int iii = 0;

    if (flag) {
        iii = 1;
    }
    else {
        iii = 0;
    }
}

int func8(int p)
{
    int r;

    switch (p) {
    case 0:
        r = 100;
        break;
    case 1:
        r = 200;
        break;
    default:
        r = 300;
        break;
    }

    return r;
}

void func9()
{
    int *p;

    try {
        p = new int[10];
    }
    catch (...) {
        p = nullptr;
    }

}

void func10()
{
    // comment
    for (int iii = 0;
        iii < NUMBER;
        ++iii)
    {
        h1 += iii; // comment
    }
}
```

Than just another idea: Is it not possible to handle only `CxxGrammarImpl.statement`? And mark only lines containing a statement as 'executable'?

**Comment by guwirth** [comment]
Hi @Bertk,

below the coverage with VS2015.3 with sample file as it is shown inside of VS:

vs1
grafik
grafik
grafik
grafik

**Try / catch:**
grafik
Throwing an exception:
grafik

**if/else:**
if
grafik
else
grafik

Regards

**Comment by Bertk** [comment]
@guwirth I think the coverage tools handle the line, statement, branch coverage differently and a better solution might consider this behavior. Microsoft coverage tool and Bullseye ccover are used by us but until now the result from the tools and SonarQube are different  :confused:
By the way, what about **_[constexpr](http://en.cppreference.com/w/cpp/language/constexpr)_** code coverage? At the moment the block is assigned to executable lines ```7, 8, 9, 17, 22, 23, 24, 25, 32, 33, 36, 42, 46, 47, 48, 50, 51, 53, 54, 55```

constexpr

I think for now the current solution should be OK and refactoring should be postponed. Maybe the [current coverage approach for executable lines](https://docs.sonarqube.org/display/DEV/Executable+Lines) is too simple and will be updated again.

see also [Bullseye: What is Wrong with Statement Coverage](http://bullseye.com/statementCoverage.html#b2)

**Comment by guwirth** [comment]
@Bertk thanks for your update.

Comparing the executable lines in the unit test with the sample code I would still propose two changes:
* Don't  mark  {} as executable.  Think not all coverage tool will mark it as covered. It's then a false positive left. In case of VS coverage report they will anyway be overwritten and green. 
* **else** should also be not marked as executable

**Comment by guwirth** [comment]
@Bertk **constexpr** looks like this in VS:

grafik

So no special handling needed.

**Comment by guwirth** [comment]
Would merge it as is.

**Pull request merged**
