### PR TITLE
Remove get child

### PR DESCRIPTION
**Pull request by guwirth**
* replace getChild(0) with getFirstChild(), getNextSibling()
* use AstNodeType to compare

### CODE REVIEW

**Comment by guwirth** [comment]
@Bertk & @jmecosta could one of you test this PR please.
Beside the functionality I'm interested in the performance.
Thx.

**Comment by jmecosta** [comment]
@guwirth it does not work. crashes with some file

[22:33:35][Step 3/3] org.sonar.runner.impl.RunnerException: Unable to execute Sonar
[22:33:35][Step 3/3] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:91)
[22:33:35][Step 3/3] 	at org.sonar.runner.impl.BatchLauncher$1.run(BatchLauncher.java:75)
[22:33:35][Step 3/3] 	at java.security.AccessController.doPrivileged(Native Method)
[22:33:35][Step 3/3] 	at org.sonar.runner.impl.BatchLauncher.doExecute(BatchLauncher.java:69)
[22:33:35][Step 3/3] 	at org.sonar.runner.impl.BatchLauncher.execute(BatchLauncher.java:50)
[22:33:35][Step 3/3] 	at org.sonar.runner.api.EmbeddedRunner.doExecute(EmbeddedRunner.java:102)
[22:33:35][Step 3/3] 	at org.sonar.runner.api.Runner.execute(Runner.java:100)
[22:33:35][Step 3/3] 	at org.sonar.runner.Main.executeTask(Main.java:70)
[22:33:35][Step 3/3] 	at org.sonar.runner.Main.execute(Main.java:59)
[22:33:35][Step 3/3] 	at org.sonar.runner.Main.main(Main.java:53)
[22:33:35][Step 3/3] Caused by: org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: E:\prod\structures\src\work\Core\Reporting\libtkitinterface\interface\tkitinterface.hpp
[22:33:35][Step 3/3] 	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:131)
[22:33:35][Step 3/3] 	at org.sonar.plugins.cxx.squid.CxxSquidSensor.analyse(CxxSquidSensor.java:136)
[22:33:35][Step 3/3] 	at org.sonar.batch.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:58)
[22:33:35][Step 3/3] 	at org.sonar.batch.phases.SensorsExecutor.execute(SensorsExecutor.java:50)
[22:33:35][Step 3/3] 	at org.sonar.batch.phases.PhaseExecutor.execute(PhaseExecutor.java:102)
[22:33:35][Step 3/3] 	at org.sonar.batch.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:185)
[22:33:35][Step 3/3] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[22:33:35][Step 3/3] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
[22:33:35][Step 3/3] 	at org.sonar.batch.scan.ProjectScanContainer.scan(ProjectScanContainer.java:264)
[22:33:35][Step 3/3] 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:259)
[22:33:35][Step 3/3] 	at org.sonar.batch.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:257)
[22:33:35][Step 3/3] 	at org.sonar.batch.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:249)
[22:33:35][Step 3/3] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[22:33:35][Step 3/3] 	at org.sonar.batch.scan.ProjectScanContainer.startComponents(ProjectScanContainer.java:127)
[22:33:35][Step 3/3] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
[22:33:35][Step 3/3] 	at org.sonar.batch.task.ScanTask.execute(ScanTask.java:55)
[22:33:35][Step 3/3] 	at org.sonar.batch.task.TaskContainer.doAfterStart(TaskContainer.java:86)
[22:33:35][Step 3/3] 	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:135)
[22:33:35][Step 3/3] 	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:120)
[22:33:35][Step 3/3] 	at org.sonar.batch.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:122)
[22:33:35][Step 3/3] 	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:119)
[22:33:35][Step 3/3] 	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:79)
[22:33:35][Step 3/3] 	at org.sonar.runner.batch.IsolatedLauncher.execute(IsolatedLauncher.java:48)
[22:33:35][Step 3/3] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[22:33:35][Step 3/3] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[22:33:35][Step 3/3] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[22:33:35][Step 3/3] 	at java.lang.reflect.Method.invoke(Method.java:498)
[22:33:35][Step 3/3] 	at org.sonar.runner.impl.BatchLauncher$1.delegateExecution(BatchLauncher.java:87)
[22:33:35][Step 3/3] 	... 9 more
[22:33:35][Step 3/3] Caused by: java.lang.IllegalStateException: java.nio.charset.MalformedInputException: Input length = 1
[22:33:35][Step 3/3] 	at org.sonar.cxx.checks.LineRegularExpressionCheck.visitFile(LineRegularExpressionCheck.java:112)
[22:33:35][Step 3/3] 	at com.sonar.sslr.impl.ast.AstWalker.walkAndVisit(AstWalker.java:67)
[22:33:35][Step 3/3] 	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:110)
[22:33:35][Step 3/3] 	... 36 more
[22:33:35][Step 3/3] Caused by: java.nio.charset.MalformedInputException: Input length = 1
[22:33:35][Step 3/3] 	at java.nio.charset.CoderResult.throwException(CoderResult.java:281)
[22:33:35][Step 3/3] 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:339)
[22:33:35][Step 3/3] 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
[22:33:35][Step 3/3] 	at java.io.InputStreamReader.read(InputStreamReader.java:184)
[22:33:35][Step 3/3] 	at java.io.BufferedReader.fill(BufferedReader.java:161)
[22:33:35][Step 3/3] 	at java.io.BufferedReader.readLine(BufferedReader.java:324)
[22:33:35][Step 3/3] 	at java.io.BufferedReader.readLine(BufferedReader.java:389)
[22:33:35][Step 3/3] 	at java.nio.file.Files.readAllLines(Files.java:3205)
[22:33:35][Step 3/3] 	at org.sonar.cxx.checks.LineRegularExpressionCheck.visitFile(LineRegularExpressionCheck.java:110)
[22:33:35][Step 3/3] 	... 38 more
[22:33:35][Step 3/3] ERROR: 
[22:33:35][Step 3/3] ERROR: Re-run SonarQube Runner using the -X switch to enable full debug logging.

**Comment by guwirth** [comment]
Hi @jmecosta thx for testing. Think the problem is not this PR. Looking to the log the problem is in https://github.com/SonarOpenCommunity/sonar-cxx/blob/master/cxx-checks/src/main/java/org/sonar/cxx/checks/LineRegularExpressionCheck.java. Maybe a problem with the charset. I think the problem occurs also in master branch?  Are there special characters e.g. in E:\prod\structures\src\work\Core\Reporting\libtkitinterface\interface\tkitinterface.hpp?

**Comment by jmecosta** [comment]
I need to check on Monday, I've reverted to latest master. Let's see, cannot get to work got ny account locked :(

**Comment by jmecosta** [comment]
yep, broken by

Author:		guwirth <guenter.wirth@etas.com>
Author date:	2 weeks ago (4.5.2016 13.42.04)
Commit date:	1 week ago (7.5.2016 11.03.11)
Commit hash:	3be7d9360b1d38673b9dcd011e1875e9bd2d4277
Children:	ee54a92b3b
Parent(s):	1407f91f5f

use Java 7 constructs and try to remove com.google.* dependencies


Contained in branches: remove-getChild, master, bugfix/fix-eclipse-bug
Contained in no tag


Perhaps those guava stuff should be reverted at least until next LTS, usually anyway usuage of immutable is prefer over normal arrays

**Comment by jmecosta** [comment]
unable to test this pr, since there are 2 many conflicts up to this change

**Comment by guwirth** [comment]
@jmecosta problem seems to be the replacement of `com.google.common.io.Files.readLines` with `java.nio.file.Files.readAllLines`, the Java version throws a `java.nio.charset.MalformedInputException`.Looking to **FileEncodingCheck.java** in the PR 3be7d9360b1d38673b9dcd011e1875e9bd2d4277 shows the difference: readLines seems to ignore wrong encodings, a second stept to find invalid characters was needed (don't know if complete file is read in this case?). readAllLines is throwing immediately in case of an encoding problem.

**So bug or feature?** I still think that parts of your source files has invalid characters/encodings? Question is also how **LineRegularExpressionCheck** should work with characters with invalid encoding?

How to continue?
* go back to `com.google.common.io.Files.readLines` and ignore encoding problem
* use `java.nio.file.Files.readAllLines` and keep current behaviour: because source file is invalid
* use `java.nio.file.Files.readAllLines`, catch `java.nio.charset.MalformedInputException` and continue
* ...

**Comment by jmecosta** [comment]
ok makes sense, my problem with it is that core is able to cope with it and provide lines metric. also i checked the LOC and its correct also for that file. So regardless of the encoding we have in that file it seems to work properly with the previous implementation

**Comment by Bertk** [comment]
I also tested the PR but could not see any performance improvement.

The encoding is stricter with this PR  3be7d93  and I modified some files (ASCII => UTF-8 without BOM). The exception were created by comments with invalid characters e.g. 'ü' which were used within some names.
We should have a relaxed encoding for comments and I do not see a benefit to fix old files which uses incorrect characters in some comments.

**Comment by jmecosta** [comment]
yes, its the same for ours. comments with some invalid chars

**Comment by guwirth** [comment]
@jmecosta there are 8 usages of ReadAllLines in the code (https://github.com/SonarOpenCommunity/sonar-cxx/search?utf8=%E2%9C%93&q=readalllines). They are all inside of checks. So rest of analysis should not be affected?

> We should have a relaxed encoding for comments and I do not see a benefit to fix old files which uses incorrect characters in some comments.

Inside of the checks it is not possible to find out what's a comment.

Possible workaround is
* to catch exception and continue
* to replace invalid signs with a placeholder and continue

Do you know how `com.google.common.io.Files.readLines` is doing it?

**Comment by jmecosta** [comment]
@guwirth just making the point that core does not crash, so we should not either

**Comment by guwirth** [comment]
Will try out today what happens with invalid characters in the Google implementation and will come back to you.

**Comment by guwirth** [comment]
What's the difference:
* read `/* ü */` with `US-ASCII` 
* `com.google.common.io.Files.readLines` returns `/* �� */`, no exception
* `java.nio.file.Files.readAllLines`: exception & list = null

**Comment by guwirth** [comment]
> I also tested the PR but could not see any performance improvement.

Main intention of this PR was to remove the deprecated getChild. From using AstNodeType to compare I expected some performance improvement because == instead of String.equals can be used now. But seems to have only minor impact on overall performance.

**Comment by guwirth** [comment]
@jmecosta changing `sonar.sourceEncoding` from `US-ASCII` to `UTF-8` should also solve the prolem?

**Comment by Bertk** [comment]
I use the setting `sonar.sourceEncoding=UTF-8` but this will not avoid the exceptions. The encoding of the source file has also to be `UTF-8 (without BOM)` as well and a better approach is log a warning instead failing the analysis.

**Comment by guwirth** [comment]
@jmecosta & @Bertk: think all points are on the table now. There are two ways to continue:

1) undo commit and use `com.google.common.io.Files.readLines` again: no exception in case of invalid encoded characters; invalid characters are replaced by a placeholder; check continue searching

2) use `java.nio.file.Files.readAllLines`: catch  and ignore `java.nio.charset.MalformedInputException` exception; log warning; result of `readAllLines` is empty; check will do nothing

Please vote

**Comment by jmecosta** [comment]
+1 1)

**Comment by Bertk** [comment]
:+1: 1)
This will not introduce any regression and replacing the invalid character will allow to continue the check.

**Comment by guwirth** [comment]
@jmecosta ready to test

**Comment by jmecosta** [comment]
@guwirth seems to be ok now, i did not see any visible performance regressions.

**Comment by jmecosta** [comment]
@guwirth notice one of our builds still failing.


[20:45:31][Step 1/1] Caused by: java.lang.NoClassDefFoundError: java/util/StringJoiner
[20:45:31][Step 1/1] 	at org.sonar.cxx.preprocessor.CxxPreprocessor.serialize(CxxPreprocessor.java:731)
[20:45:31][Step 1/1] 	at org.sonar.cxx.preprocessor.CxxPreprocessor.serialize(CxxPreprocessor.java:727)
[20:45:31][Step 1/1] 	at org.sonar.cxx.preprocessor.CxxPreprocessor.handleIdentifiersAndKeywords(CxxPreprocessor.java:613)
[20:45:31][Step 1/1] 	at org.sonar.cxx.preprocessor.CxxPreprocessor.process(CxxPreprocessor.java:371)
[20:45:31][Step 1/1] 	at com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:158)
[20:45:31][Step 1/1] 	at com.sonar.sslr.impl.Lexer.preprocess(Lexer.java:148)
[20:45:31][Step 1/1] 	at com.sonar.sslr.impl.Lexer.lex(Lexer.java:137)
[20:45:31][Step 1/1] 	at com.sonar.sslr.impl.Lexer.lex(Lexer.java:96)
[20:45:31][Step 1/1] 	at com.sonar.sslr.impl.Lexer.lex(Lexer.java:82)
[20:45:31][Step 1/1] 	at com.sonar.sslr.impl.Parser.parse(Parser.java:68)
[20:45:31][Step 1/1] 	at org.sonar.squidbridge.AstScanner.scanFiles(AstScanner.java:94)
[20:45:31][Step 1/1] 	... 35 more
[20:45:31][Step 1/1] Process exited with code 1
[20:45:34][Step 1/1] Step SonarRunner (Command Line) failed

NoClassDefFoundError for string joiner, wasnt something you have been working or removing drepecated stuff?

**Comment by guwirth** [comment]
@jmecosta `StringJoiner` is Java 8 (https://docs.oracle.com/javase/8/docs/api/java/util/StringJoiner.html)

and still in use here: https://github.com/SonarOpenCommunity/sonar-cxx/blob/42f0627242c616f3e6a75765b31664c2b1fea830/cxx-squid/src/main/java/org/sonar/cxx/preprocessor/CxxPreprocessor.java#L731

**Comment by jmecosta** [comment]
yep good point, teamcity is injecting a java 7 home to the runner.

[20:44:37][Step 1/1] JAVA_HOME=C:\BuildAgent\jre
[20:44:37][Step 1/1] JDK_17=C:\Program Files (x86)\Java\jdk1.7.0_55
[20:44:37][Step 1/1] JDK_18=C:\Program Files\Java\jdk1.8.0_05
[20:44:37][Step 1/1] JDK_18_x64=C:\Program Files\Java\jdk1.8.0_05
[20:44:37][Step 1/1] JDK_HOME=C:\Program Files\Java\jdk1.8.0_05
[20:44:37][Step 1/1] JRE_HOME=C:\Program Files\Java\jdk1.8.0_05

thanks.

**Pull request merged**
